FROM ubuntu:22.04

RUN apt update && apt install -y openssh-server sudo
RUN useradd -m -s /bin/bash ansible && echo "ansible:ansible" | chpasswd && adduser ansible sudo
RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]